env:
  global:
  - TERM=dumb
language: java
jdk: oraclejdk8
addons:
  apt:
    update: true
    packages:
    - curl
    - jq
    - bash
    - python-pip
install: true
before_install:
- sudo pip install httpie >/dev/null 2>&1
- source <(curl -fsSL https://raw.github.com/daggerok/bash-functions/master/main.bash)
- stop_any 80 8000 8080 8081 8082 8083 8001 8002 8003
- echo "org.gradle.console=auto" > gradle.properties
script:
- bash gradlew -b ./docs/build.gradle asciidoctor || true # travis / gradle, wtf?!
- export root=$(pwd)
- bash gradlew -S
- bash apps/oauth2-jdbc/auth-server/build/libs/*.jar &
- bash apps/oauth2-jdbc/resource-server/build/libs/*.jar &
- bash apps/oauth2-jdbc/web-client-app/build/libs/*.jar &
- wait_for 8001 8002 8003
- access_token=$(http -a clientId:secret --form post :8001/oauth/token grant_type=password username=usr password=pwd | jq .access_token)
- echo "access token -- $access_token"
- access_token="${access_token%\"}" # remove prefixed (left) quote
- access_token="${access_token#\"}" # remove suffixed (right) quote
- echo "access token -- $access_token"
- http -a clientId:secret --form post :8001/oauth/check_token token=$access_token
- secured_content=$(http :8002/ Authorization:"Bearer $access_token" | jq .ololo)
- echo "secured content -- $secured_content"
- stop_any 80 8000 8080 8081 8082 8083 8001 8002 8003
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
