
////
:apps:oauth2-jdbc:resource-server README.adoc
////

=== resource server

Now we ready to go with link:{github-url}/tree/master/apps/jdbc-oauth2-resource-server/[building `jdbc-oauth2-resource-server`]

.build, run and test
[source,bash]
----
./gradlew :apps:oauth2-jdbc:resource-server:bootRun
----

=== implementation

. implement resource server `/check_token` remote token service endpoint: link:./#RemoteTokenServicesConfig[`RemoteTokenServicesConfig`]

==== remote token services

[[RemoteTokenServicesConfig]]

.RemoteTokenServicesConfig
[source,java]
----
include::./src/main/java/com/github/daggerok/oauth2resourceserver/JdbcOauth2ResourceServer.java[tags=remote-token-services-config]
----

=== testing

Let's test how clients can access resource-server resources using obtained token from auth-server....

.first, clint must obtain active token
[source,bash]
----
http -a clientId:secret --form post :8001/oauth/token grant_type=password username=usr password=pwd
----

.response ouptu
[source,json]
----
{
    "access_token": "be5caf90-f197-43bf-86e2-cd4560066871",
    "expires_in": 40917,
    "refresh_token": "4b2991af-6e1b-40cc-ab83-3f0c135d8c12",
    "scope": "read",
    "token_type": "bearer"
}
----

Now client can use received access_token value to query resource-server /

.test unauthorized forst
[source,bash]
----
http :8002/
----

.response ouptu
[source,json]
----
{
    "error": "unauthorized",
    "error_description": "Full authentication is required to access this resource"
}
----

.now let's use access_token to get resource-server data
[source,bash]
----
http :8002/ Authorization:'Bearer be5caf90-f197-43bf-86e2-cd4560066871'
----

.response ouptu
[source,json]
----
{
    "at": "2018-06-03T01:20:45.153Z",
    "ololo": "trololo"
}
----

Done!

////

---
links:

- link:https://docs.spring.io/spring-security-oauth2-boot/docs/2.0.1.RELEASE/reference/html5/#common-application-properties[authorization server reference]
- link:http://www.baeldung.com/rest-api-spring-oauth2-angularjs[get some thought from here...]
- link:https://github.com/sharmaritesh/oauth2-spring-boot-mongo[auth/resource servers some examples]
- link:https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.0-Migration-Guide[Migration guide to spring-boot 2.x]

////
