spring:
  datasource:
    url: jdbc:h2:~/security-first;AUTO_SERVER=TRUE;MULTI_THREADED=TRUE;Mode=MySQL;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: security-first
    password: security-first
    driver-class-name: org.h2.Driver
    hikari:
      connection-test-query: 'SELECT 1;'
  h2.console.enabled: true
logging.level.org.springframework.jdbc: 'DEBUG'
